Completed react-form-controls
annaaksenov/m2-0723-code-solutions pull request #22
Opened 2023-09-10 00:45 UTC by annaaksenov

react-form-controls - Anna Aksenov
![Screenshot (165)](https://github.com/annaaksenov/m2-0723-code-solutions/assets/121647003/95130f44-93f4-4741-9ae0-741538787449)

2023-09-12 04:38 UTC, ninajhun requested changes

2023-09-12 04:38 UTC, ninajhun commented on react-form-controls/my-app/src/RegistrationFormUncontrolled.jsx
> +    const usrnm = document.querySelector('#usrnm').value;
I would use `event.target` instead to avoid unnecessary DOM transversals as pass that instead to create your `formData`

2023-09-12 04:38 UTC, ninajhun commented on react-form-controls/my-app/src/RegistrationFormUncontrolled.jsx
> +    for (const pair of formData.entries()) {
You can simplify here and use `Object.fromEntries(formData.entries()) `  to get the individual field values instead

2023-09-12 04:38 UTC, ninajhun commented on react-form-controls/my-app/src/RegistrationFormUncontrolled.jsx
> +  function handleSubmit(event) {
Please review step 5 of the exercise and refactor with the below comments. Let us know if you have any questions in slack!

2023-09-12 04:38 UTC, ninajhun commented on react-form-controls/my-app/src/RegistrationFormControlled.jsx
> +  const [isUsername, setUsername] = useState('');
No need to update for now, but using "is" as in  `isUsername` is typically used to denote a boolean by many developers as a shorthand! 

I recommend sticking to `username` and `password` next time! 💡

2023-09-12 04:38 UTC, ninajhun commented on react-form-controls/my-app/src/RegistrationFormControlled.jsx
> +    let isUsername = event.target.isUsername;
`isUsername` is already declared as a state value. If we want to change its value, we need to use the `setUsername` function to update it.

Also, to make this function more reusable, use `event.target.value` instead. I encourage you to `console.log(event.target)` and take a look at all the properties and methods!

2023-09-13 03:43 UTC, scbowler approved these changes
Great job implementing the feedback, looks good! 👍

2023-09-14 17:07 UTC, merged